{
  "type": "record",
  "name": "Customer",
  "namespace": "com.example.bikecustomservise.api.schema",
  "fields": [
    {
      "doc": "number version",
      "name": "version",
      "type": "int"
    },
    {
      "name": "dateTime",
      "type": "int"
    },
    {
      "name": "customerName",
      "type": "string"
    },
    {
      "name": "customerEmail",
      "type": "string"
    },
    {
      "name": "orderName",
      "type": "string",
    },
    {
      "name": "orderPrice",
      "type": "double"
    }

  ]
}