{
  "type": "record",
  "name": "Envelope",
  "namespace": "com.example.bikecustomservise.api.schema",
  "fields": [
    {
      "doc": "number version",
      "name": "version",
      "type": "int"
    },
    {
      "doc": "Algoritmn of hash",
      "name": "sign_alg",
      "type": "string"
    },
    {
      "doc": "Hash",
      "name": "sign",
      "type": "bytes"
    },
    {
      "doc": "Avro for publish",
      "name": "m_container",
      "type": {
        "items": com.com.example.bikecustomservise.api.schema.Customer,
        "type": "bytes"
      }
    }
  ]
}